name: coderspace
description: "A Flutter widget package by **CoderSpace** offering beautifully designed, customizable, and reusable components including animated borders, styled buttons, app bars, containers, text fields, and auto-scrolling images."
version: 1.0.0
homepage: https://github.com/coderspacedev/coderspace_flutter
repository: https://github.com/coderspacedev/coderspace_flutter
issue_tracker: https://github.com/coderspacedev/coderspace_flutter/issues
documentation: https://github.com/coderspacedev/coderspace_flutter#readme
environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
