name: coderspace
description: "A Flutter package by CoderSpace with reusable widgets like app bars, buttons, text fields, containers, and animated borders."
version: 1.0.8
homepage: https://github.com/coderspacedev
repository: https://github.com/coderspacedev/coderspace_flutter
issue_tracker: https://github.com/coderspacedev/coderspace_flutter/issues
documentation: https://github.com/coderspacedev/coderspace_flutter#readme
environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
